### ISSUE TITLE
no module name gpiod

### ISSUE THREAD

**Issue by iomari** [sgjava/userspaceio#9] opened 2020-02-25 09:07 UTC
Greetings,
I've installed userspaceio on several tinkerboards and beagleboneblacks.
No visble errors on installing but when in python, each in sbc returns the error "no module named gpiod" when I run any code that imports gpiod.

What am I doing wrong?
iomari

**Comment by sgjava** [comment] 2020-02-25 21:32
Duplicate of #6

**Closed by sgjava** 2020-02-25 21:32 UTC
